#! /usr/bin/env bash

# xl: xl gimp image batch filter
# Copyright (C) 2012 Juan Manuel Borges Caño

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# cd images/

fopin="$1" # file directory in images
fop="$2" # scale seamless enhance emboss oilify cartoon mosaic cubism sharpen sobel laplace edgesobel edgelaplace neon dog noise spread desaturate softglow gauss 

shift 2

for dir in "$@"
do
	echo "$dir"
	cd "$dir"
	for file in *.*
	do
		cd "${file%%.*}"
		../../xl-gimp "$fop" "${file%%.*}-${fopin^}.jpg"
		cd ..
	done
	cd ..
done
